-- Articles module in the controlling area
-- Run this in the Supabase SQL editor (or via `supabase db push`) BEFORE deploying the frontend.
-- The old frontend keeps working: it only reads article rows.
--
-- Context: public.article was created in the dashboard (id, external_id, name,
-- piecework_wage, piecework_packaging, ...) and is not under version control.
-- Nobody could create or change articles through the app.
--
--   1. column types: external_id becomes text if it is not; piecework_wage / piecework_packaging must be numeric
--   2. guard: refuses to run while existing data would break the new constraints
--   3. id: make sure inserts get an id (identity), if the dashboard did not set one up
--   4. master data columns: unit, notes, active; constraints on number, name, unit and wages
--   5. RLS: read stays open to all authenticated users; insert/update/delete admin only
--   6. foreign keys referencing article block the delete, so an article with reports or
--      deliveries cannot be deleted, only archived
--   7. article_private (1:1 with article): sales price, admin only
--   8. save_article(p_id, p_article, p_private)  admin-only atomic create/update of both rows

-- 1. Column types
do $$
declare
    col record;
begin
    for col in
        select a.attname, format_type(a.atttypid, a.atttypmod) as type_name, t.typcategory
        from pg_attribute a
        join pg_type t on t.oid = a.atttypid
        where a.attrelid = 'public.article'::regclass
          and a.attname in ('external_id', 'piecework_wage', 'piecework_packaging')
          and a.attnum > 0
          and not a.attisdropped
    loop
        if col.attname = 'external_id' and col.typcategory <> 'S' then
            execute 'alter table public.article alter column external_id type text using external_id::text';
            raise notice 'article.external_id changed from % to text', col.type_name;
        elsif col.attname <> 'external_id' and col.typcategory <> 'N' then
            raise exception 'article.% has type %, expected a number. Adjust this migration before running it.',
                col.attname, col.type_name;
        end if;
    end loop;
end;
$$;

alter table public.article
    add column if not exists external_id text,
    add column if not exists piecework_wage numeric,
    add column if not exists piecework_packaging numeric;

-- 2. Guard
do $$
declare
    problems text;
begin
    select string_agg(problem, E'\n') into problems
    from (
        select format('article %s: article number (external_id) is empty', id) as problem
        from public.article
        where nullif(trim(external_id), '') is null
        union all
        select format('article number %L is used by articles %s', trim(external_id), string_agg(id::text, ', '))
        from public.article
        where nullif(trim(external_id), '') is not null
        group by trim(external_id)
        having count(*) > 1
        union all
        select format('article %s: name is empty', id)
        from public.article
        where nullif(trim(name), '') is null
        union all
        select format('article %s: piecework_wage %s is negative', id, piecework_wage)
        from public.article
        where piecework_wage < 0
        union all
        select format('article %s: piecework_packaging %s is negative', id, piecework_packaging)
        from public.article
        where piecework_packaging < 0
    ) p;

    if problems is not null then
        raise exception E'Fix these article rows before running this migration:\n%', problems;
    end if;
end;
$$;

update public.article set external_id = trim(external_id) where external_id <> trim(external_id);
update public.article set name = trim(name) where name <> trim(name);

-- 3. id identity
do $$
begin
    if exists (
        select 1
        from pg_attribute a
        where a.attrelid = 'public.article'::regclass
          and a.attname = 'id'
          and a.attidentity = ''
          and not a.atthasdef
    ) then
        alter table public.article alter column id add generated by default as identity;
        perform setval(
            pg_get_serial_sequence('public.article', 'id'),
            coalesce((select max(id) from public.article), 0) + 1,
            false
        );
    end if;
end;
$$;

-- 4. Master data
alter table public.article
    add column if not exists unit text not null default 'piece',
    add column if not exists notes text,
    add column if not exists active boolean not null default true;

alter table public.article alter column external_id set not null;
alter table public.article alter column name set not null;

comment on column public.article.external_id is 'Article number shown in pickers and on the delivery note. Required, unique, free text.';
comment on column public.article.piecework_wage is
    'Piecework wage per unit in EUR. Payroll uses the current value, also when earlier months are recalculated.';
comment on column public.article.unit is 'Unit code (piece, kg, crate, box, pallet, bunch); labels are translated in the app.';
comment on column public.article.active is
    'Archived articles (false) are no longer offered in the report, timestamp and delivery pickers but stay on existing entries.';

create unique index if not exists article_external_id_key on public.article (external_id);

alter table public.article drop constraint if exists article_external_id_check;
alter table public.article
    add constraint article_external_id_check check (trim(external_id) <> '');

alter table public.article drop constraint if exists article_name_check;
alter table public.article
    add constraint article_name_check check (trim(name) <> '');

alter table public.article drop constraint if exists article_unit_check;
alter table public.article
    add constraint article_unit_check check (unit in ('piece', 'kg', 'crate', 'box', 'pallet', 'bunch'));

alter table public.article drop constraint if exists article_piecework_wage_check;
alter table public.article
    add constraint article_piecework_wage_check check (piecework_wage >= 0);

alter table public.article drop constraint if exists article_piecework_packaging_check;
alter table public.article
    add constraint article_piecework_packaging_check check (piecework_packaging >= 0);

-- 5. RLS
-- Enabling RLS without a select policy would hide every article, so make sure one exists.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'article'
          and cmd in ('SELECT', 'ALL')
    ) then
        create policy "Authenticated select on article"
        on public.article
        for select
        to authenticated
        using (true);
    end if;
end;
$$;

alter table public.article enable row level security;

drop policy if exists "Admin insert on article" on public.article;
create policy "Admin insert on article"
on public.article
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin update on article" on public.article;
create policy "Admin update on article"
on public.article
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin delete on article" on public.article;
create policy "Admin delete on article"
on public.article
for delete
to authenticated
using (public.is_admin());

-- 6. Foreign keys to article must block the delete (article_private, created below, keeps its cascade)
do $$
declare
    fk record;
begin
    for fk in
        select c.conrelid::regclass as tbl, c.conname, pg_get_constraintdef(c.oid) as def
        from pg_constraint c
        where c.contype = 'f'
          and c.confrelid = 'public.article'::regclass
          and c.conrelid <> coalesce(to_regclass('public.article_private'), 0::regclass)
          and c.confdeltype in ('c', 'n', 'd') -- cascade, set null, set default
    loop
        execute format('alter table %s drop constraint %I', fk.tbl, fk.conname);
        execute format(
            'alter table %s add constraint %I %s',
            fk.tbl,
            fk.conname,
            regexp_replace(fk.def, 'ON DELETE (CASCADE|SET NULL|SET DEFAULT)( \([^)]*\))?', 'ON DELETE RESTRICT')
        );
        raise notice 'Foreign key %.% now uses on delete restrict', fk.tbl, fk.conname;
    end loop;
end;
$$;

-- 7. Private article data
create table if not exists public.article_private (
    article_id bigint primary key references public.article(id) on delete cascade,
    sales_price numeric(10, 2) check (sales_price >= 0),
    updated_at timestamptz not null default now()
);

comment on table public.article_private is 'Admin-only article data (commercially sensitive). One row per article.';
comment on column public.article_private.sales_price is 'Net sales price in EUR per article unit.';

alter table public.article_private enable row level security;

drop policy if exists "Admin all on article_private" on public.article_private;
create policy "Admin all on article_private"
on public.article_private
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- 8. Atomic save
create or replace function public.save_article(p_id bigint, p_article jsonb, p_private jsonb)
returns bigint
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
    v_id bigint := p_id;
    a public.article;
    p public.article_private;
begin
    if not public.is_admin() then
        raise exception 'Article data is restricted to administrators'
            using errcode = '42501';
    end if;

    a := jsonb_populate_record(null::public.article, p_article);
    p := jsonb_populate_record(null::public.article_private, p_private);

    if v_id is null then
        insert into public.article (external_id, name, unit, piecework_wage, piecework_packaging, notes, active)
        values (
            a.external_id, a.name, coalesce(a.unit, 'piece'), a.piecework_wage, a.piecework_packaging,
            a.notes, coalesce(a.active, true)
        )
        returning id into v_id;
    else
        update public.article
        set external_id = a.external_id,
            name = a.name,
            unit = coalesce(a.unit, 'piece'),
            piecework_wage = a.piecework_wage,
            piecework_packaging = a.piecework_packaging,
            notes = a.notes,
            active = coalesce(a.active, true)
        where id = v_id;

        if not found then
            raise exception 'Article % not found', v_id
                using errcode = 'P0002';
        end if;
    end if;

    insert into public.article_private (article_id, sales_price, updated_at)
    values (v_id, p.sales_price, now())
    on conflict (article_id) do update
    set sales_price = excluded.sales_price,
        updated_at = now();

    return v_id;
end;
$$;

comment on function public.save_article(bigint, jsonb, jsonb) is
    'Admin only. Creates (p_id null) or fully replaces an article and its article_private row in one transaction. Returns the article id.';

revoke all on function public.save_article(bigint, jsonb, jsonb) from public;
grant execute on function public.save_article(bigint, jsonb, jsonb) to authenticated;
