-- Customers module in the controlling area
-- Run this in the Supabase SQL editor (or via `supabase db push`) BEFORE deploying the frontend.
-- The old frontend keeps working: it only reads id and name.
--
-- Context: public.customer was created in the dashboard with only id, name and
-- created_at and a single policy "Enable read access for all auth users" (select).
-- Nobody could create or change customers through the app.
--
--   1. id: make sure inserts get an id (identity), if the dashboard did not set one up
--   2. master data columns: customer number, main address, billing address, payment term, contact, notes, active
--   3. constraints: customer number unique when set, sane values
--   4. RLS: read stays open to all authenticated users; insert/update/delete admin only
--   5. foreign keys referencing customer block the delete (no cascade / set null), so a
--      customer with deliveries cannot be deleted, only archived

-- 1. id identity
do $$
begin
    if exists (
        select 1
        from pg_attribute a
        where a.attrelid = 'public.customer'::regclass
          and a.attname = 'id'
          and a.attidentity = ''
          and not a.atthasdef
    ) then
        alter table public.customer alter column id add generated by default as identity;
        perform setval(
            pg_get_serial_sequence('public.customer', 'id'),
            coalesce((select max(id) from public.customer), 0) + 1,
            false
        );
    end if;
end;
$$;

-- 2. Master data
alter table public.customer
    add column if not exists customer_number integer,
    add column if not exists address_street text,
    add column if not exists address_house_number text,
    add column if not exists address_zip_code text,
    add column if not exists address_city text,
    add column if not exists address_country text default 'DE',
    add column if not exists billing_differs boolean not null default false,
    add column if not exists billing_name text,
    add column if not exists billing_street text,
    add column if not exists billing_house_number text,
    add column if not exists billing_zip_code text,
    add column if not exists billing_city text,
    add column if not exists billing_country text,
    add column if not exists payment_term_days integer,
    add column if not exists vat_id text,
    add column if not exists email text,
    add column if not exists phone text,
    add column if not exists contact_person text,
    add column if not exists notes text,
    add column if not exists active boolean not null default true;

comment on column public.customer.customer_number is
    'Customer number (e.g. DATEV debtor number). Optional, unique when set, entered by hand.';
comment on column public.customer.address_country is 'ISO 3166-1 alpha-2 country code, e.g. DE.';
comment on column public.customer.billing_differs is
    'When false the billing_* fields are empty and the main address is used for billing.';
comment on column public.customer.billing_country is 'ISO 3166-1 alpha-2 country code, e.g. DE.';
comment on column public.customer.payment_term_days is 'Payment term in days (net).';
comment on column public.customer.active is
    'Archived customers (false) are no longer offered in the delivery picker but stay on existing deliveries.';

-- 3. Constraints
create unique index if not exists customer_customer_number_key
    on public.customer (customer_number)
    where customer_number is not null;

alter table public.customer drop constraint if exists customer_customer_number_check;
alter table public.customer
    add constraint customer_customer_number_check check (customer_number > 0);

alter table public.customer drop constraint if exists customer_payment_term_days_check;
alter table public.customer
    add constraint customer_payment_term_days_check check (payment_term_days >= 0);

alter table public.customer drop constraint if exists customer_address_country_check;
alter table public.customer
    add constraint customer_address_country_check check (address_country ~ '^[A-Z]{2}$');

alter table public.customer drop constraint if exists customer_billing_country_check;
alter table public.customer
    add constraint customer_billing_country_check check (billing_country ~ '^[A-Z]{2}$');

-- 4. RLS
alter table public.customer enable row level security;

drop policy if exists "Admin insert on customer" on public.customer;
create policy "Admin insert on customer"
on public.customer
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin update on customer" on public.customer;
create policy "Admin update on customer"
on public.customer
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin delete on customer" on public.customer;
create policy "Admin delete on customer"
on public.customer
for delete
to authenticated
using (public.is_admin());

-- 5. Foreign keys to customer must block the delete
do $$
declare
    fk record;
begin
    for fk in
        select c.conrelid::regclass as tbl, c.conname, pg_get_constraintdef(c.oid) as def
        from pg_constraint c
        where c.contype = 'f'
          and c.confrelid = 'public.customer'::regclass
          and c.confdeltype in ('c', 'n', 'd') -- cascade, set null, set default
    loop
        execute format('alter table %s drop constraint %I', fk.tbl, fk.conname);
        execute format(
            'alter table %s add constraint %I %s',
            fk.tbl,
            fk.conname,
            regexp_replace(fk.def, 'ON DELETE (CASCADE|SET NULL|SET DEFAULT)( \([^)]*\))?', 'ON DELETE RESTRICT')
        );
        raise notice 'Foreign key %.% now uses on delete restrict', fk.tbl, fk.conname;
    end loop;
end;
$$;
